### ISSUE TITLE
Heros: Height props partly not working properly

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/ruhmesmeile#31] opened 2024-11-07 11:57 UTC
`Fullimage` or `Fullscreen` Height props are buggy.

**Comment by julrich** [comment] 2024-11-18 11:30
Those now seem to work as intended, should be reviewed though.

I've added the following content to test:
https://www.ruhmesmeile.com/playground

Follow-up issue about `height` set to `small` having no real effect on mobile breakpoints:
https://github.com/kickstartDS/ds-agency-premium/issues/21

**Comment by julrich** [comment] 2024-11-26 09:27
Closing this, as it seems to be working as intended to me.

**Closed by julrich** 2024-11-26 09:27 UTC
Labels: bug, help wanted
